routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/sports', "sportsController",[
    'names' => [
        'index' => 'sports',
        'show' => 'sports/{id}'
    ]
]);
Route::get('/',"sportsController@index");
Route::resource('/upload', "uploadFilesController",[
    'names' => [
        'store' => 'upload',
    ]
]);

resources/views/basketBall.blade.php
@extends("layouts.sports")
@section("sportContent")
<h4>BasketBall</h4>
<a class="btn btn-danger" 
onclick="event.preventDefault(); $('#delete-form').submit();">
  Clear All
</a>
<form  id="delete-form" action="{{route('sports.destroy',$activeSportKey)}}" 
  method="post"> 
@csrf @method('DELETE') 
</form> 
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Match</th>
        <th scope="col">Player</th>
        <th scope="col">position</th>
        <th scope="col">team</th>
        <th scope="col">scored points</th>
        <th scope="col">Rebound</th>
        <th scope="col">Assists</th>
        <th scope="col">Score</th>
      </tr>



    </thead>
    <tbody>
        
      @foreach ($matchesDetails as $key => $matchDetail)
      @php
      $winPlayersObj = $winningPlayers->where('matches_id',$matchDetail->match_id)
     ->where('players_id',$matchDetail->players_id)->first();   
     $winTeamObj = $winningTeams->where('matches_id',$matchDetail->match_id)
     ->where('sports_teams_id',$matchDetail->team_id)->first(); 
     @endphp
     
      <tr>
      <td>{{$matchDetail->match_name}}</td>
      @if(!is_null($winPlayersObj) &&
      $winPlayersObj->players_id == $matchDetail->players_id)
      <td class="table-success">
      @else
      <td>
      @endif
      {{$matchDetail->player_name}}</td>
      <td>{{$matchDetail->positions}}</td>
      @if (!is_null($winTeamObj) && $winTeamObj->sports_teams_id== $matchDetail->team_id)
      <td class="table-success">
          @else
          <td>
      @endif
      {{$matchDetail->team_name}}</td>
      <td>{{$matchDetail->scored_points}}</td>
      <td>{{$matchDetail->rebounds}}</td>
      <td>{{$matchDetail->assist}}</td>
      @if (!is_null($winTeamObj) && $winTeamObj->sports_teams_id== $matchDetail->team_id)
      <td class="table-success">
          @else
          <td>
      @endif
      {{$matchDetail->score}}</td>
      </tr>
      @endforeach
    </tbody>
  </table>
  @endsection

resources/views/exceptions.blade.php
@extends("layouts.main")
<div class="alert alert-danger">
{{$msg}}
</div>

resources/views/handBall.blade.php
@extends("layouts.sports")
@section("sportContent")
<h4>HandBall</h4>
<a class="btn btn-danger" 
onclick="event.preventDefault(); $('#delete-form').submit();">
  Clear All
</a>
<form  id="delete-form" action="{{route('sports.destroy',$activeSportKey)}}" 
  method="post"> 
@csrf @method('DELETE') 
</form> 
@php
// if(!isset($matchDetail)){die();}
// if(!isset($winningPlayers)){$winningPlayers = null;}
// if(!isset($winningTeams)){$winningTeams = null;}    
@endphp
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Match</th>
        <th scope="col">Player</th>
        <th scope="col">position</th>
        <th scope="col">team</th>
        <th scope="col">scored points</th>
        <th scope="col">Rebound</th>
        <th scope="col">Assists</th>
        <th scope="col">Score</th>
      </tr>



    </thead>
    <tbody>
       
      @foreach ($matchesDetails as $key => $matchDetail)
      @php
       $winPlayersObj = $winningPlayers->where('matches_id',$matchDetail->match_id)
      ->where('players_id',$matchDetail->players_id)->first();   
      $winTeamObj = $winningTeams->where('matches_id',$matchDetail->match_id)
      ->where('sports_teams_id',$matchDetail->team_id)->first(); 
      @endphp
      {{-- < ?php dd($matchDetail->match_name); ?> --}}
       {{-- < ?php dd($winningPlayers->where('matches_id',$matchDetail->match_id)->where('players_id',$matchDetail->players_id)); ?>  --}}
      
      <tr>
      <td>{{$matchDetail->match_name}}</td>
      {{-- < ?php var_dump($winningPlayers->where('matches_id',$matchDetail->match_id)->where('players_id',$matchDetail->players_id)); ?> --}}
      
      @if(!is_null($winPlayersObj) &&
      $winPlayersObj->players_id == $matchDetail->players_id)
      <td class="table-success">
      @else
      <td>
      @endif
      {{$matchDetail->player_name}}</td>
      <td>{{$matchDetail->positions}}</td>
      @if (!is_null($winTeamObj) && $winTeamObj->sports_teams_id== $matchDetail->team_id)
      <td class="table-success">
          @else
          <td>
      @endif
      {{$matchDetail->team_name}}</td>
      <td>{{$matchDetail->scored_points}}</td>
      <td>{{$matchDetail->rebounds}}</td>
      <td>{{$matchDetail->assist}}</td>
      @if (!is_null($winTeamObj) && $winTeamObj->sports_teams_id== $matchDetail->team_id)
      <td class="table-success">
          @else
          <td>
      @endif
      {{$matchDetail->score}}</td>
      </tr>
      @endforeach
    </tbody>
  </table>
  @endsection

resources/views/uploadFiles.blade.php
@extends("layouts.main")
<div>
    <h3>Upload Matches:</h3>
    <div class="UploadContent">
      <button onclick="addNewFileUpload()" class="newMatchBtn">New Match</button>
    
    
<form id="uploadSportsForm" action="{{route("upload")}}" 
method="post" enctype="multipart/form-data">
    @csrf
    <div id="inputFiles" class="inputFiles">
    <input  type="file" name="fileToUpload" id="fileToUpload">
    </div>
    <input type="submit" class="UploadSubmitBtn" value="Upload" name="submit">
  </form>
</div>
</div>
@if($errors->any())
<div class="alert alert-danger">
@foreach ($errors->all() as $error)
{{$error}}
</br>
@endforeach
</div>
@endif